{
 "title": "FinOps Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "My application total costs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_allocation_bytes{namespace=\"demo\", pod=~\"rollouts-demo-.*\"})/1024/1024/1024 * ignoring(instance, job, node) node_ram_hourly_cost + {__name__=~\"mycloud_db_[0-9]*_current_iops\", tribe=\"mycompany-12345\", stage=\"dev\"} * ignoring(instance, job,stage,tribe) mycloud_db_cost + sum(container_cpu_allocation{namespace=\"demo\", pod=~\"rollouts-demo-.*\"}) * ignoring(instance, job, node) node_cpu_hourly_cost"
    }
   ]
  },
  {
   "title": "VM summary cost",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"mycloud_vm_[0-9]{10}_current_cost\"})"
    }
   ]
  },
  {
   "title": "My application cost by resource",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_allocation{namespace=\"demo\", pod=~\"rollouts-demo-.*\"}) * ignoring(instance, job, node) node_cpu_hourly_cost",
     "legendFormat": "My application CPU cost"
    },
    {
     "expr": "{__name__=~\"mycloud_db_[0-9]*_current_iops\", tribe=\"mycompany-12345\", stage=\"dev\"} * ignoring(instance, job,stage,tribe) mycloud_db_cost",
     "legendFormat": "MyCloud DB cost"
    },
    {
     "expr": "sum(container_memory_allocation_bytes{namespace=\"demo\", pod=~\"rollouts-demo-.*\"})/1024/1024/1024 * ignoring(instance, job, node) node_ram_hourly_cost",
     "legendFormat": "My application RAM cost"
    }
   ]
  }
 ]
}